language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_NAME=Nexus_5X_API_22
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
    - NODE_VERSION=8.7.0

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-22
install:
  - android list targets
  - echo no | android create avd -f -n $ANDROID_NAME -t $ANDROID_TARGET -b $ANDROID_ABI
  - nvm install $NODE_VERSION;
  - nvm use --delete-prefix $NODE_VERSION;
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn
script:
  - npm run start & PACKAGER_PID=$!
  - emulator -avd $ANDROID_NAME -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - npm run e2e:android
after_failure:
  - kill -9 $PACKAGER_PID
after_success:
  - kill -9 $PACKAGER_PID
